name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Deploy to EC2 via rsync
        uses: burnett01/rsync-deployments@v5.2
        with:
          switches: -avzr --delete
          path: |
            .next
            public
            package.json
            package-lock.json
            next.config.*
          remote_path: /home/ubuntu/instadl_frontend
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.EC2_SSH_KEY }}

      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/instadl_frontend
            npm ci --omit=dev
            pm2 restart instadl-frontend || pm2 start npm --name instadl-frontend -- start
            pm2 save
